<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechHaven.Domain\TechHaven.Domain.csproj" />
    <ProjectReference Include="..\TechHaven.Shared\TechHaven.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />

    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />

    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />

    <PackageReference Include="MediatR" Version="11.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />

    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
  </ItemGroup>

</Project>
